# Generated by Django 5.1.7 on 2025-04-01 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('competences_requises', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=100)),
                ('cause', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/')),
                ('document', models.FileField(blank=True, null=True, upload_to='missions/docs/')),
                ('association', models.ForeignKey(limit_choices_to={'type_utilisateur': 'association'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
