# Generated by Django 5.1.7 on 2025-04-01 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='capacite_max',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='mission',
            name='inscrits',
            field=models.ManyToManyField(blank=True, related_name='missions_inscrites', to=settings.AUTH_USER_MODEL),
        ),
    ]
