# Generated by Django 5.1.7 on 2025-04-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_competence_benevole_listeattente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('verifie', models.BooleanField(default=False)),
            ],
        ),
    ]
