# Generated by Django 5.1.7 on 2025-04-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_alter_listeattente_benevole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
