# Generated by Django 5.1.7 on 2025-04-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_historiqueparticipation_delete_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiqueparticipation',
            name='role',
        ),
    ]
