# Generated by Django 5.1.7 on 2025-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0013_remove_historiqueparticipation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_valid', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
