# Generated by Django 5.1.7 on 2025-04-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0014_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
