# Generated by Django 5.1.7 on 2025-04-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_mission_urgent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('validee', models.BooleanField(default=False)),
            ],
        ),
    ]
