# Generated by Django 5.1.7 on 2025-04-06 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0015_mission_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
