# Generated by Django 5.1.7 on 2025-04-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
